#!/usr/bin/env python3
import subprocess, os, atexit
from time import sleep
from termcolors import *

def exit_handler():
    os.system('clear')

def Main():
    atexit.register(exit_handler)
    os.system('setterm -cursor off')
    old_users = []
    while True:
        users = []
        ps = subprocess.Popen(['ps', '-au'], stdout=subprocess.PIPE).communicate()[0].decode('utf-8').splitlines()
        for p in ps:
            if "dxbdxb7" in p:
                users.append(p.split()[0])
        if users != old_users:
            os.system('clear')
            users = list(set(users))
            print(yellow + "online: (" + str(len(users)) + ")" + default)
            print("\n".join(users))
            old_users = users[:]
        sleep(1)
    
if __name__ == "__main__":
    Main()
