#!/usr/bin/env python3

##################################
# this is the top pane of the chat
# it reads the log file and can
# be sent commands to execute
##################################

import subprocess
import os
from termcolors import *

userid = os.getlogin()

def welcome():
    print(bold + "-----------------> " + white\
        + "+++" + red + " /TMP/.SCHAT " + white + "+++ "\
        + blue + underline + "love yourself." + default)

def tail():
    filename = "/tmp/.schat.log"
    proc = subprocess.Popen(['tail', '-F', filename],\
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    running = True
    while running:
        line = proc.stdout.readline().rstrip().decode('utf-8')
        # replaces current userid to red
        line = line.replace(userid + ":", red + userid + ":" + default)
        print(line)


def Main():
    welcome()
    tail()

if __name__ == '__main__':
    Main()
