#!/usr/bin/env python3
import subprocess
import os

# foreground colors for the terminal
black =    "\033[30m"
white =    "\033[97m"
red =      "\033[31m"
green =    "\033[32m"
yellow =   "\033[33m"
blue =     "\033[34m"
magenta =  "\033[35m"
cyan =     "\033[36m"
lgray =    "\033[37m"
dgray =    "\033[90m"
lred =     "\033[91m"
lgreen =   "\033[92m"
lyellow =  "\033[93m"
lblue =    "\033[94m"
lmagenta = "\033[95m"
lcyan =    "\033[96m"

# background colors for the terminal
bgblack =    "\033[40m"
bgwhite =    "\033[107m"
bgred =      "\033[41m"
bggreen =    "\033[42m"
bgyellow =   "\033[43m"
bgblue =     "\033[44m"
bgmagenta =  "\033[45m"
bgcyan =     "\033[46m"
bglgray =    "\033[47m"
bgdgray =    "\033[100m"
bglred =     "\033[101m"
bglgreen =   "\033[102m"
bglyellow =  "\033[103m"
bglblue =    "\033[104m"
bglmagenta = "\033[105m"
bglcyan =    "\033[106m"
bgdefault =  "\033[49m"

# styles for the terminal
default =    "\033[0m"
bold =       "\033[1m"
rbold =      "\033[21m" #reset
dim =        "\033[2m"
rdim =       "\033[22m" #reset
underline =  "\033[4m"
runderline = "\033[24m" #reset
blink =      "\033[5m"
rblink =     "\033[25m" #reset
invert =     "\033[7m"
rinvert =    "\033[27m" #reset
hidden =     "\033[8m"

userid = os.getlogin()

def welcome():
    print(bold + "-----------------> " + white\
        + "+++" + red + " /TMP/.SCHAT " + white + "+++ "\
        + blue + underline + "love yourself." + default)

def tail():
    filename = "/tmp/.schat.log"
    proc = subprocess.Popen(['tail', '-F', filename],\
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    running = True
    while running:
        line = proc.stdout.readline().rstrip().decode('utf-8')
        # replaces current userid to red
        line = line.replace(userid + ":", red + userid + ":" + default)
        print(line)


def Main():
    welcome()
    tail()

if __name__ == '__main__':
    Main()
