#!/usr/bin/env python3

##################################
# this is the top pane of the chat
# it reads the log file and can
# be sent commands to execute
##################################

import subprocess
import os, sys
import datetime
import time
from termcolors import *

userid = os.getlogin()

def welcome():
    print(bgwhite + bold + " ----------------> " + black\
        + "+++" + red + " /TMP/.SCHAT " + black + "+++ "\
        + blue + underline + "love yourself." + default + " " + bgdefault)

def thetime():
    return datetime.datetime.now().strftime("[%Y-%m-%d %H:%M]");

def tail():
    filename = "/tmp/.schat.log"
    proc = subprocess.Popen(['tail', '-F', filename],\
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    running = True
    while running:
        line = proc.stdout.readline().rstrip().decode('utf-8')
        # execution calls begin with %#
        if line[:2] == "%#":
            line = line.split()
            command_time = float(line[1])
            command_user = line[2]
            # second argument is unix time stamp.
            # this compares, and if current time is greater
            # than time.time()+delay sent, then run command
            # otherwise ignore
            if command_time >= time.time():
                if line[0] == "%#deletelog":
                    os.system('clear')
                    print(thetime() + bold + red + " --- LOG CLEARED BY " + line[2] + " ---" + default)
                elif line[0] =="%#colortest":
                    colortest()

                elif line[0] == "%#listusers" and command_user == userid:
                    listusers()
        else:
            # replaces current userid to red
            line = line.replace(userid + ":", red + userid + ":" + default)
            print(line)

def colortest():
    for i in range(0, 16):
        for j in range(0, 16):
            code = str(i * 16 + j)
            sys.stdout.write("\033[48;5;" + code + "m " + code.ljust(4))
        print("\033[0m")

def listusers():
    users = []
    ps = subprocess.Popen(['ps', '-au'], stdout=subprocess.PIPE).communicate()[0].decode('utf-8').splitlines()
    for p in ps:
        if "schat.sh" in p:
            users.append(p.split()[0])
    print(thetime() + bold + yellow + " Users Online: " + rbold + blue + ", ".join(list(set(users))) + default)

def Main():
    welcome()
    tail()

if __name__ == '__main__':
    Main()
